apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nodejs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-nodejs-app
  template:
    metadata:
      labels:
        app: my-nodejs-app
    spec:
      containers:
      - name: my-nodejs-app
        image: girish2722/my-nodejs-app:latest
        ports:
        - containerPort: 3000 # Replace with your application's port
---
apiVersion: v1
kind: Service
metadata:
  name: my-nodejs-app-service
spec:
  selector:
    app: my-nodejs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000 # Replace with your application's port
  type: LoadBalancer # Change to NodePort if you're not using a cloud provider
